package main

import (
	"fmt"
	"os"
	"strings"
)

func readPassphrase(decrypt bool) (pass string, err error) {
	if decrypt {
		pass, err = readSecret("Enter passphrase:")
		return
	}

	pass, err = readSecret("Enter passphrase (leave empty to autogenerate a secure one):")
	if err != nil {
		return
	}

	if pass == "" {
		var words []string
		for i := 0; i < 10; i++ {
			words = append(words, randomWord())
		}

		pass = strings.Join(words, "-")
		err = withTerminal(func(in, out *os.File) error {
			_, e := fmt.Fprintf(out, "Using autogenerated passphrase: %q\n", pass)
			return e
		})

		return
	}

	if confirm, err := readSecret("Confirm passphrase:"); err != nil {
		return "", err
	} else if confirm != pass {
		return "", fmt.Errorf("passphrase confirmation does not match")
	}

	return
}
